#1 ログイン機能作成
CST-araihara/cst-keijiban pull request #3
Opened 2022-10-04 07:54 UTC by CST-Oshima

### リクエスト概要
#1 

### 対応内容の詳細
管理者ログイン→管理ページ
ユーザーログイン→ユーザーページ
ログイン失敗時のエラーメッセージ表示
10回以上パスワードを間違えた際のロック及び解除

### closeするissue番号
close #1

### 備考
userテーブルにdisable_flagとfalse_count列追加
headerとfooterのパス変更

2022-10-04 08:09 UTC, teiq0223 requested changes
指摘箇所の修正をお願いします

2022-10-04 08:09 UTC, teiq0223 commented on htdocs/migrations/20221004111528_UsersTestDataAdd.php
> +<?php
テーブル初期作成のmigrationファイルに追記してください

2022-10-04 08:09 UTC, teiq0223 commented on htdocs/migrations/20221004151706_UsersTestDataAdd2.php
> +<?php
テーブル初期作成のmigrationファイルに追記してください

2022-10-04 08:09 UTC, teiq0223 commented on htdocs/model/login_model.php
> +    $password = 'password';
共通化

2022-10-05 00:04 UTC, teiq0223 requested changes
指摘箇所の修正をお願いします

2022-10-05 00:04 UTC, teiq0223 commented on htdocs/migrations/20221003145543_CreateTable.php
>              comment varchar(100) NULL,
createのマイグレーションファイルはテーブル単位で分けて下さい

2022-10-05 00:04 UTC, teiq0223 commented on htdocs/model/login_model.php
> +}
* 環境に依存する値については、コンフィグファイルに定義してそれを呼び出す形に変更
* connect()については、全部の機能で同じように利用されるものであるため、全部のファイルから一か所を呼び出せるように作ってください

2022-10-05 02:16 UTC, YuukiTakemasa approved these changes
LGTM

2022-10-05 02:16 UTC, merged